# Generated by Django 5.2.3 on 2025-07-20 23:26

import datetime
import django.db.models.deletion
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
                ('license_number', models.CharField(max_length=45)),
                ('license_state', localflavor.us.models.USStateField(max_length=2)),
                ('license_exp_date', models.DateField()),
                ('driver_start_date', models.DateField(default=datetime.date(2025, 1, 1), verbose_name='Hire date')),
                ('driver_end_date', models.DateField(blank=True, null=True, verbose_name='Termination date')),
                ('driver_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_number', models.CharField(max_length=45)),
                ('trailer_vin_number', models.CharField(max_length=45)),
                ('trailer_year', models.CharField(max_length=45)),
                ('trailer_make', models.CharField(max_length=45)),
                ('trailer_plate_number', models.CharField(max_length=45)),
                ('trailer_plate_state', localflavor.us.models.USStateField(max_length=2)),
                ('trailer_start_date', models.DateField(default=datetime.date(2025, 1, 1))),
                ('trailer_end_date', models.DateField(blank=True, null=True, verbose_name='Termination date')),
                ('truck_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=45)),
                ('truck_vin_number', models.CharField(max_length=45)),
                ('truck_year', models.CharField(max_length=45)),
                ('truck_make', models.CharField(max_length=45)),
                ('truck_plate_number', models.CharField(max_length=45)),
                ('truck_plate_state', localflavor.us.models.USStateField(max_length=2)),
                ('truck_start_date', models.DateField(default=datetime.date(2025, 1, 1))),
                ('truck_end_date', models.DateField(blank=True, null=True, verbose_name='Termination date')),
                ('truck_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_number', models.CharField(max_length=45)),
                ('location_pickup', models.CharField(max_length=45)),
                ('location_delivery', models.CharField(max_length=45)),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('total_cost', models.IntegerField()),
                ('load_status_delivered', models.BooleanField(blank=True, default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_date', models.DateField()),
                ('total_pay', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.driver')),
            ],
        ),
    ]
