# Generated by Django 5.2.3 on 2025-07-30 23:45

import django.db.models.deletion
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='load_status_delivered',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_pay',
        ),
        migrations.AddField(
            model_name='payroll',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Driver active'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=45, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_exp_date',
            field=models.DateField(verbose_name='CDL exp date'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=45, verbose_name='CDL #'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_state',
            field=localflavor.us.models.USStateField(max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='load',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_app.driver'),
        ),
        migrations.AlterField(
            model_name='load',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
